version: "3.7"
services:
  db:
    image: mysql:8
    ports:
      - 3000:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass
      - MYSQL_DATABASE=app
  btt-symf:
    image: gusdecool/symfony
    volumes:
      - ~/.composer:/root/.composer
      - ./:/app
    ports:
      - 3001:80
      - 3002:443
    depends_on:
      - db
volumes:
  mysql_data:
    driver: local
  yarn_cache:
